
export type ButtonPropControl =
    | "text"
    | "boolean"
    | "select"
    | "slider"
    | "color"

export interface ButtonPropDefinition {
    control: ButtonPropControl
    default: string | number | boolean
    description: string
    options?: string[]
    min?: number
    max?: number
}

export interface ButtonSectionMeta {
    slug: string
    name: string
    componentName: string
    description: string
    tags: string[]
    props: Record<string, ButtonPropDefinition>
    category: string
}

const defaultButtonProps: Record<string, ButtonPropDefinition> = {
    children: {
        control: "text",
        default: "Button",
        description: "The text to display on the button.",
    },
}

const buttonWithClassNameProps: Record<string, ButtonPropDefinition> = {
    ...defaultButtonProps,
    className: {
        control: "text",
        default: "",
        description: "Additional CSS classes to apply to the button.",
    },
}

// Extended props for buttons that support more customization
const extendedButtonProps: Record<string, ButtonPropDefinition> = {
    ...defaultButtonProps,
    className: {
        control: "text",
        default: "",
        description: "Additional CSS classes to apply to the button.",
    },
    size: {
        control: "select",
        default: "default",
        options: ["sm", "default", "lg"],
        description: "The size of the button.",
    },
    borderRadius: {
        control: "slider",
        default: 8,
        min: 0,
        max: 24,
        description: "Border radius in pixels.",
    },
    paddingX: {
        control: "slider",
        default: 32,
        min: 8,
        max: 64,
        description: "Horizontal padding in pixels.",
    },
    paddingY: {
        control: "slider",
        default: 12,
        min: 4,
        max: 32,
        description: "Vertical padding in pixels.",
    },
    backgroundColor: {
        control: "color",
        default: "",
        description: "Background color of the button.",
    },
    textColor: {
        control: "color",
        default: "",
        description: "Text color of the button.",
    },
    borderColor: {
        control: "color",
        default: "",
        description: "Border color of the button.",
    },
    borderWidth: {
        control: "slider",
        default: 0,
        min: 0,
        max: 4,
        description: "Border width in pixels.",
    },
}

export const buttonSections: ButtonSectionMeta[] = [
    {
        slug: "magnetic-button",
        name: "Magnetic Button",
        componentName: "MagneticButton",
        description: "A button that magnetically follows the cursor movement.",
        tags: ["button", "magnetic", "hover", "interaction"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "glitch-button",
        name: "Glitch Button",
        componentName: "GlitchButton",
        description: "A button with a digital glitch effect on hover.",
        tags: ["button", "glitch", "effect", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "liquid-hover-button",
        name: "Liquid Hover Button",
        componentName: "LiquidHoverButton",
        description: "A button with a liquid fill effect on hover.",
        tags: ["button", "liquid", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "neumorphic-button",
        name: "Neumorphic Button",
        componentName: "NeumorphicButton",
        description: "A button designed with soft UI / neumorphism style.",
        tags: ["button", "neumorphic", "soft-ui", "shadow"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "gradient-border-button",
        name: "Gradient Border Button",
        componentName: "GradientBorderButton",
        description: "A button with a gradient border.",
        tags: ["button", "gradient", "border", "colorful"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "shimmer-button",
        name: "Shimmer Button",
        componentName: "ShimmerButton",
        description: "A button with a shimmering light effect.",
        tags: ["button", "shimmer", "shine", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "pulse-glow-button",
        name: "Pulse Glow Button",
        componentName: "PulseGlowButton",
        description: "A button that pulses with a glowing effect.",
        tags: ["button", "pulse", "glow", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "slide-arrow-button",
        name: "Slide Arrow Button",
        componentName: "SlideArrowButton",
        description: "A button where an arrow slides in on hover.",
        tags: ["button", "arrow", "slide", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "three-d-press-button",
        name: "3D Press Button",
        componentName: "ThreeDPressButton",
        description: "A button with a 3D press effect.",
        tags: ["button", "3d", "press", "click"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "ripple-button",
        name: "Ripple Button",
        componentName: "RippleButton",
        description: "A button with a material design ripple effect.",
        tags: ["button", "ripple", "material", "click"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "ghost-hover-button",
        name: "Ghost Hover Button",
        componentName: "GhostHoverButton",
        description: "A transparent button that fills on hover.",
        tags: ["button", "ghost", "hover", "transparent"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "status-loading-button",
        name: "Status Loading Button",
        componentName: "StatusLoadingButton",
        description: "A button that shows loading and success states.",
        tags: ["button", "loading", "status", "feedback"],
        props: {
            buttonText: {
                control: "text",
                default: "Submit",
                description: "The text to display when the button is idle.",
            },
        },
        category: "Button",
    },
    {
        slug: "spotlight-button",
        name: "Spotlight Button",
        componentName: "SpotlightButton",
        description: "A button with a spotlight effect that follows the cursor.",
        tags: ["button", "spotlight", "hover", "light"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "pixel-art-button",
        name: "Pixel Art Button",
        componentName: "PixelArtButton",
        description: "A retro pixel art style button.",
        tags: ["button", "pixel", "retro", "8bit"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "glassmorphism-button",
        name: "Glassmorphism Button",
        componentName: "GlassmorphismButton",
        description: "A button with a frosted glass effect.",
        tags: ["button", "glassmorphism", "glass", "blur"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "neon-flicker-button",
        name: "Neon Flicker Button",
        componentName: "NeonFlickerButton",
        description: "A button with a neon flickering text effect.",
        tags: ["button", "neon", "flicker", "glow"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "elastic-button",
        name: "Elastic Button",
        componentName: "ElasticButton",
        description: "A button with an elastic scaling effect.",
        tags: ["button", "elastic", "scale", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "copy-clipboard-button",
        name: "Copy Clipboard Button",
        componentName: "CopyClipboardButton",
        description: "A button to copy text to clipboard with feedback.",
        tags: ["button", "copy", "clipboard", "utility"],
        props: {
            copyText: {
                control: "text",
                default: "Copy Code",
                description: "The text to display on the button.",
            },
        },
        category: "Button",
    },
    {
        slug: "social-share-button",
        name: "Social Share Button",
        componentName: "SocialShareButton",
        description: "A button that expands to show social share icons.",
        tags: ["button", "social", "share", "expand"],
        props: buttonWithClassNameProps,
        category: "Button",
    },
    {
        slug: "download-progress-button",
        name: "Download Progress Button",
        componentName: "DownloadProgressButton",
        description: "A button that visualizes download progress.",
        tags: ["button", "download", "progress", "animation"],
        props: {
            downloadText: {
                control: "text",
                default: "Download",
                description: "The text to display on the button.",
            },
        },
        category: "Button",
    },
    {
        slug: "swipe-right-button",
        name: "Swipe Right Button",
        componentName: "SwipeRightButton",
        description: "A button with a swipe right fill effect.",
        tags: ["button", "swipe", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "swipe-up-button",
        name: "Swipe Up Button",
        componentName: "SwipeUpButton",
        description: "A button with a swipe up fill effect.",
        tags: ["button", "swipe", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "scale-up-button",
        name: "Scale Up Button",
        componentName: "ScaleUpButton",
        description: "A button with a scale up fill effect.",
        tags: ["button", "scale", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "draw-border-button",
        name: "Draw Border Button",
        componentName: "DrawBorderButton",
        description: "A button where the border is drawn on hover.",
        tags: ["button", "border", "draw", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "dotted-border-button",
        name: "Dotted Border Button",
        componentName: "DottedBorderButton",
        description: "A button with a dotted border that changes on hover.",
        tags: ["button", "border", "dotted", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "gradient-ring-button",
        name: "Gradient Ring Button",
        componentName: "GradientRingButton",
        description: "A button with a gradient ring border.",
        tags: ["button", "gradient", "ring", "border"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "cyber-button",
        name: "Cyber Button",
        componentName: "CyberButton",
        description: "A cyberpunk style button with clipped corners.",
        tags: ["button", "cyber", "cyberpunk", "futuristic"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "retro-95-button",
        name: "Retro 95 Button",
        componentName: "Retro95Button",
        description: "A Windows 95 style retro button.",
        tags: ["button", "retro", "95", "windows"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "clay-button",
        name: "Clay Button",
        componentName: "ClayButton",
        description: "A button with a claymorphism style.",
        tags: ["button", "clay", "claymorphism", "soft"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "skeuo-button",
        name: "Skeuo Button",
        componentName: "SkeuoButton",
        description: "A skeuomorphic button with depth.",
        tags: ["button", "skeuomorphic", "depth", "3d"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "shake-error-button",
        name: "Shake Error Button",
        componentName: "ShakeErrorButton",
        description: "A button that shakes to indicate an error.",
        tags: ["button", "shake", "error", "feedback"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "confetti-button",
        name: "Confetti Button",
        componentName: "ConfettiButton",
        description: "A button that triggers a confetti burst.",
        tags: ["button", "confetti", "celebration", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "hold-button",
        name: "Hold Button",
        componentName: "HoldButton",
        description: "A button that requires holding to confirm.",
        tags: ["button", "hold", "confirm", "interaction"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "delete-button",
        name: "Delete Button",
        componentName: "DeleteButton",
        description: "A delete button with a confirmation step.",
        tags: ["button", "delete", "confirm", "danger"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "like-button",
        name: "Like Button",
        componentName: "LikeButton",
        description: "A like button with heart animation.",
        tags: ["button", "like", "heart", "toggle"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "skew-button",
        name: "Skew Button",
        componentName: "SkewButton",
        description: "A skewed button style.",
        tags: ["button", "skew", "transform", "style"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "blob-button",
        name: "Blob Button",
        componentName: "BlobButton",
        description: "A button with an organic blob shape.",
        tags: ["button", "blob", "organic", "shape"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "underline-button",
        name: "Underline Button",
        componentName: "UnderlineButton",
        description: "A button with an animated underline.",
        tags: ["button", "underline", "hover", "text"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "bracket-button",
        name: "Bracket Button",
        componentName: "BracketButton",
        description: "A button with animated brackets.",
        tags: ["button", "bracket", "hover", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "curtain-button",
        name: "Curtain Button",
        componentName: "CurtainButton",
        description: "A button with a curtain reveal effect.",
        tags: ["button", "curtain", "reveal", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "slice-button",
        name: "Slice Button",
        componentName: "SliceButton",
        description: "A button with a slicing effect.",
        tags: ["button", "slice", "hover", "effect"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "wet-paint-button",
        name: "Wet Paint Button",
        componentName: "WetPaintButton",
        description: "A button that looks like wet paint.",
        tags: ["button", "wet", "paint", "style"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "particle-button",
        name: "Particle Button",
        componentName: "ParticleButton",
        description: "A button with particle effects.",
        tags: ["button", "particle", "effect", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "isometric-button",
        name: "Isometric Button",
        componentName: "IsometricButton",
        description: "An isometric 3D button.",
        tags: ["button", "isometric", "3d", "perspective"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "paper-fold-button",
        name: "Paper Fold Button",
        componentName: "PaperFoldButton",
        description: "A button that looks like folded paper.",
        tags: ["button", "paper", "fold", "style"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "text-fill-button",
        name: "Text Fill Button",
        componentName: "TextFillButton",
        description: "A button where the text fills with color.",
        tags: ["button", "text", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "icon-slide-button",
        name: "Icon Slide Button",
        componentName: "IconSlideButton",
        description: "A button where an icon slides in.",
        tags: ["button", "icon", "slide", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "multi-layer-button",
        name: "Multi Layer Button",
        componentName: "MultiLayerButton",
        description: "A button with multiple layers.",
        tags: ["button", "layer", "stack", "3d"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "upload-button",
        name: "Upload Button",
        componentName: "UploadButton",
        description: "A button designed for file uploads.",
        tags: ["button", "upload", "file", "action"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "toggle-switch-button",
        name: "Toggle Switch Button",
        componentName: "ToggleSwitchButton",
        description: "A toggle switch button.",
        tags: ["button", "toggle", "switch", "control"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "swipe-left-button",
        name: "Swipe Left Button",
        componentName: "SwipeLeftButton",
        description: "A button with a swipe left fill effect.",
        tags: ["button", "swipe", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "swipe-down-button",
        name: "Swipe Down Button",
        componentName: "SwipeDownButton",
        description: "A button with a swipe down fill effect.",
        tags: ["button", "swipe", "fill", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "double-border-button",
        name: "Double Border Button",
        componentName: "DoubleBorderButton",
        description: "A button with a double border.",
        tags: ["button", "border", "double", "style"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "spinning-border-button",
        name: "Spinning Border Button",
        componentName: "SpinningBorderButton",
        description: "A button with a spinning border effect.",
        tags: ["button", "border", "spin", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "letter-spacing-button",
        name: "Letter Spacing Button",
        componentName: "LetterSpacingButton",
        description: "A button that increases letter spacing on hover.",
        tags: ["button", "text", "spacing", "hover"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "blur-reveal-button",
        name: "Blur Reveal Button",
        componentName: "BlurRevealButton",
        description: "A button that reveals content from blur.",
        tags: ["button", "blur", "reveal", "effect"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "vaporwave-button",
        name: "Vaporwave Button",
        componentName: "VaporwaveButton",
        description: "A vaporwave aesthetic button.",
        tags: ["button", "vaporwave", "aesthetic", "retro"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "save-button",
        name: "Save Button",
        componentName: "SaveButton",
        description: "A standard save button with icon.",
        tags: ["button", "save", "icon", "action"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "print-button",
        name: "Print Button",
        componentName: "PrintButton",
        description: "A standard print button with icon.",
        tags: ["button", "print", "icon", "action"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "notification-button",
        name: "Notification Button",
        componentName: "NotificationButton",
        description: "A notification button with a badge.",
        tags: ["button", "notification", "badge", "icon"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "circle-to-square-button",
        name: "Circle to Square Button",
        componentName: "CircleToSquareButton",
        description: "A button that morphs from circle to square.",
        tags: ["button", "morph", "shape", "animation"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "morph-fab-button",
        name: "Morph FAB Button",
        componentName: "MorphFabButton",
        description: "A floating action button that morphs on hover.",
        tags: ["button", "fab", "morph", "floating"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "shiny-reflection-button",
        name: "Shiny Reflection Button",
        componentName: "ShinyReflectionButton",
        description: "A button with a shiny reflection effect.",
        tags: ["button", "shiny", "reflection", "effect"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "dot-hover-button",
        name: "Dot Hover Button",
        componentName: "DotHoverButton",
        description: "A button with a dot indicator on hover.",
        tags: ["button", "dot", "hover", "indicator"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "text-marquee-button",
        name: "Text Marquee Button",
        componentName: "TextMarqueeButton",
        description: "A button with scrolling marquee text.",
        tags: ["button", "marquee", "text", "scroll"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "scramble-text-button",
        name: "Scramble Text Button",
        componentName: "ScrambleTextButton",
        description: "A button with scrambled text effect.",
        tags: ["button", "scramble", "text", "effect"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "typewriter-button",
        name: "Typewriter Button",
        componentName: "TypewriterButton",
        description: "A button with typewriter text effect.",
        tags: ["button", "typewriter", "text", "effect"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "liquid-blob-button",
        name: "Liquid Blob Button",
        componentName: "LiquidBlobButton",
        description: "A button with a liquid blob background.",
        tags: ["button", "liquid", "blob", "background"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "cyber-punk-glitch-2-button",
        name: "CyberPunk Glitch 2 Button",
        componentName: "CyberPunkGlitch2Button",
        description: "Another cyberpunk style glitch button.",
        tags: ["button", "cyberpunk", "glitch", "effect"],
        props: extendedButtonProps,
        category: "Button",
    },
    {
        slug: "rounded-corner-morph-button",
        name: "Rounded Corner Morph Button",
        componentName: "RoundedCornerMorphButton",
        description: "A button that morphs corner radius on hover.",
        tags: ["button", "morph", "corner", "radius"],
        props: extendedButtonProps,
        category: "Button",
    },
]
